// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: comments.proto

package comments

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommentsClient is the client API for Comments service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentsClient interface {
	CommentAdd(ctx context.Context, in *CommentAddRequest, opts ...grpc.CallOption) (*CommentAddResponse, error)
	CommentGetByID(ctx context.Context, in *CommentGetByIDRequest, opts ...grpc.CallOption) (*CommentGetByIDResponse, error)
	CommentEdit(ctx context.Context, in *CommentEditRequest, opts ...grpc.CallOption) (*CommentEditResponse, error)
	CommentListBySKU(ctx context.Context, in *CommentListBySKURequest, opts ...grpc.CallOption) (*CommentListBySKUResponse, error)
	CommentListByUser(ctx context.Context, in *CommentListByUserRequest, opts ...grpc.CallOption) (*CommentListByUserResponse, error)
}

type commentsClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentsClient(cc grpc.ClientConnInterface) CommentsClient {
	return &commentsClient{cc}
}

func (c *commentsClient) CommentAdd(ctx context.Context, in *CommentAddRequest, opts ...grpc.CallOption) (*CommentAddResponse, error) {
	out := new(CommentAddResponse)
	err := c.cc.Invoke(ctx, "/Comments/CommentAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentsClient) CommentGetByID(ctx context.Context, in *CommentGetByIDRequest, opts ...grpc.CallOption) (*CommentGetByIDResponse, error) {
	out := new(CommentGetByIDResponse)
	err := c.cc.Invoke(ctx, "/Comments/CommentGetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentsClient) CommentEdit(ctx context.Context, in *CommentEditRequest, opts ...grpc.CallOption) (*CommentEditResponse, error) {
	out := new(CommentEditResponse)
	err := c.cc.Invoke(ctx, "/Comments/CommentEdit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentsClient) CommentListBySKU(ctx context.Context, in *CommentListBySKURequest, opts ...grpc.CallOption) (*CommentListBySKUResponse, error) {
	out := new(CommentListBySKUResponse)
	err := c.cc.Invoke(ctx, "/Comments/CommentListBySKU", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentsClient) CommentListByUser(ctx context.Context, in *CommentListByUserRequest, opts ...grpc.CallOption) (*CommentListByUserResponse, error) {
	out := new(CommentListByUserResponse)
	err := c.cc.Invoke(ctx, "/Comments/CommentListByUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentsServer is the server API for Comments service.
// All implementations must embed UnimplementedCommentsServer
// for forward compatibility
type CommentsServer interface {
	CommentAdd(context.Context, *CommentAddRequest) (*CommentAddResponse, error)
	CommentGetByID(context.Context, *CommentGetByIDRequest) (*CommentGetByIDResponse, error)
	CommentEdit(context.Context, *CommentEditRequest) (*CommentEditResponse, error)
	CommentListBySKU(context.Context, *CommentListBySKURequest) (*CommentListBySKUResponse, error)
	CommentListByUser(context.Context, *CommentListByUserRequest) (*CommentListByUserResponse, error)
	mustEmbedUnimplementedCommentsServer()
}

// UnimplementedCommentsServer must be embedded to have forward compatible implementations.
type UnimplementedCommentsServer struct {
}

func (UnimplementedCommentsServer) CommentAdd(context.Context, *CommentAddRequest) (*CommentAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentAdd not implemented")
}
func (UnimplementedCommentsServer) CommentGetByID(context.Context, *CommentGetByIDRequest) (*CommentGetByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentGetByID not implemented")
}
func (UnimplementedCommentsServer) CommentEdit(context.Context, *CommentEditRequest) (*CommentEditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentEdit not implemented")
}
func (UnimplementedCommentsServer) CommentListBySKU(context.Context, *CommentListBySKURequest) (*CommentListBySKUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentListBySKU not implemented")
}
func (UnimplementedCommentsServer) CommentListByUser(context.Context, *CommentListByUserRequest) (*CommentListByUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentListByUser not implemented")
}
func (UnimplementedCommentsServer) mustEmbedUnimplementedCommentsServer() {}

// UnsafeCommentsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentsServer will
// result in compilation errors.
type UnsafeCommentsServer interface {
	mustEmbedUnimplementedCommentsServer()
}

func RegisterCommentsServer(s grpc.ServiceRegistrar, srv CommentsServer) {
	s.RegisterService(&Comments_ServiceDesc, srv)
}

func _Comments_CommentAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentsServer).CommentAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Comments/CommentAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentsServer).CommentAdd(ctx, req.(*CommentAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comments_CommentGetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentGetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentsServer).CommentGetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Comments/CommentGetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentsServer).CommentGetByID(ctx, req.(*CommentGetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comments_CommentEdit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentEditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentsServer).CommentEdit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Comments/CommentEdit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentsServer).CommentEdit(ctx, req.(*CommentEditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comments_CommentListBySKU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentListBySKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentsServer).CommentListBySKU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Comments/CommentListBySKU",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentsServer).CommentListBySKU(ctx, req.(*CommentListBySKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Comments_CommentListByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentListByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentsServer).CommentListByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Comments/CommentListByUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentsServer).CommentListByUser(ctx, req.(*CommentListByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Comments_ServiceDesc is the grpc.ServiceDesc for Comments service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Comments_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Comments",
	HandlerType: (*CommentsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommentAdd",
			Handler:    _Comments_CommentAdd_Handler,
		},
		{
			MethodName: "CommentGetByID",
			Handler:    _Comments_CommentGetByID_Handler,
		},
		{
			MethodName: "CommentEdit",
			Handler:    _Comments_CommentEdit_Handler,
		},
		{
			MethodName: "CommentListBySKU",
			Handler:    _Comments_CommentListBySKU_Handler,
		},
		{
			MethodName: "CommentListByUser",
			Handler:    _Comments_CommentListByUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comments.proto",
}
