### Добавление валидного SKU в корзину
POST http://localhost:8080/user/628594270478096874/cart/1625903
Content-Type: application/json

{
  "count": 1
}
### expected {} 200 OK; must add 1 item

### Добавление валидного SKU в корзину
POST http://localhost:8080/user/628594270478096874/cart/1148162
Content-Type: application/json

{
  "count": 1
}
### expected {} 200 OK; must add 1 item

### Добавление валидного SKU в корзину
POST http://localhost:8080/user/628594270478096874/cart/1076963
Content-Type: application/json

{
  "count": 1
}
### expected {} 200 OK; must add 1 item

### Проверка корзины пользователя 628594270478096874
GET http://localhost:8080/user/628594270478096874/cart
Content-Type: application/json
### expected {json} 200 OK;

#### Очистка полной корзины
#DELETE http://localhost:8080/user/628594270478096874/cart
#Content-Type: application/json
#### expected {} 204 OK;