### Добавление товара в корзину
POST http://localhost:8080/user/31337/cart/1076963
Content-Type: application/json

{
  "count": 1
}
### expected {} 200 OK;

### Добавление товара в корзину повторно
POST http://localhost:8080/user/31337/cart/1076963
Content-Type: application/json

{
  "count": 3
}
### expected {} 200 OK;

### Добавление еще одного товара
POST http://localhost:8080/user/31337/cart/2618151
Content-Type: application/json

{
  "count": 3
}
### expected {} 200 OK;

### Добавление  товара в другую корзину
POST http://localhost:8080/user/41447/cart/2618151
Content-Type: application/json

{
  "count": 3
}
### expected {} 200 OK;

### Проверка корзины пользователя 31337
GET http://localhost:8080/user/31337/cart
Content-Type: application/json
### expected {json} 200 OK;

### Проверка корзины пользователя 41447
GET http://localhost:8080/user/41447/cart
Content-Type: application/json
### expected {json} 200 OK;

### Проверка корзины eсли корзины нет либо она пуста
GET http://localhost:8080/user/3000/cart
Content-Type: application/json
### expected {} 404 OK;

### Удаление товара из корзины
DELETE http://localhost:8080/user/31337/cart/1076963
Content-Type: application/json
### expected {} 200 OK;

### Очистка корзины
DELETE http://localhost:8080/user/41447/cart
Content-Type: application/json
### expected {} 200 OK;

### Удаление несуществующего SKU из корзины
DELETE http://localhost:8080/user/31337/cart/2565544
Content-Type: application/json
### expected {} 200 OK;

### Удаление SKU с нулевым или отрицательным значением
DELETE http://localhost:8080/user/31337/cart/-1
Content-Type: application/json
### expected {} 400 OK;

### Добавление SKU с нулевым или отрицательным значением
POST http://localhost:8080/user/31337/cart/-1
Content-Type: application/json

{
  "count": 1
}
### expected {} 400 OK;

### expected {} 400 OK;
### Добавление валидного SKU для пользователя (user_id) с нулевым или отрицательным значением
POST http://localhost:8080/user/0/cart/1076963
Content-Type: application/json

{
  "count": 1
}
### expected {} 400 OK;

### Добавление SKU с нулевым или отрицательным количеством (count)
POST http://localhost:8080/user/31337/cart/1076963
Content-Type: application/json

{
  "count": -100
}
### expected {} 400 OK;

### Добавление несуществующего SKU в корзину
POST http://localhost:8080/user/31337/cart/3380
Content-Type: application/json

{
  "count": 12
}
### expected {} 412 OK;

###  Добавление в корзину
POST http://localhost:8080/user/7652906241826593180/cart/1076963000
Content-Type: application/json

{
  "count": 12
}
#### expected {} 412 OK;

###  Добавление в корзину
POST http://localhost:8080/user/7652906241826593180/cart/9223372036854775807
Content-Type: application/json

{
  "count": 12
}
#### expected {} 412 OK;

### Добавление товара в корзину
POST http://localhost:8080/user/9223372036854775807/cart/1148162
Content-Type: application/json

{
  "count": 1
}
### expected {} 200 OK;