### get product info  by sku
GET http://localhost:8082/product/1076963
Content-Type: application/json
X-API-KEY: testToken

{

  "sku": "1076963"
}

### get list sku
GET http://localhost:8082/product?count=10&start_after_sku=0
Content-Type: application/json
X-API-KEY: testToken

{

"sku": "1076963"
}