// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mock

//go:generate minimock -i route256/loms/internal/domain/service.KafkaProducer -o kafka_producer_mock.go -n KafkaProducerMock -p mock

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// KafkaProducerMock implements mm_service.KafkaProducer
type KafkaProducerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSendMessage          func(orderID int64, status string)
	funcSendMessageOrigin    string
	inspectFuncSendMessage   func(orderID int64, status string)
	afterSendMessageCounter  uint64
	beforeSendMessageCounter uint64
	SendMessageMock          mKafkaProducerMockSendMessage
}

// NewKafkaProducerMock returns a mock for mm_service.KafkaProducer
func NewKafkaProducerMock(t minimock.Tester) *KafkaProducerMock {
	m := &KafkaProducerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendMessageMock = mKafkaProducerMockSendMessage{mock: m}
	m.SendMessageMock.callArgs = []*KafkaProducerMockSendMessageParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mKafkaProducerMockSendMessage struct {
	optional           bool
	mock               *KafkaProducerMock
	defaultExpectation *KafkaProducerMockSendMessageExpectation
	expectations       []*KafkaProducerMockSendMessageExpectation

	callArgs []*KafkaProducerMockSendMessageParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// KafkaProducerMockSendMessageExpectation specifies expectation struct of the KafkaProducer.SendMessage
type KafkaProducerMockSendMessageExpectation struct {
	mock               *KafkaProducerMock
	params             *KafkaProducerMockSendMessageParams
	paramPtrs          *KafkaProducerMockSendMessageParamPtrs
	expectationOrigins KafkaProducerMockSendMessageExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// KafkaProducerMockSendMessageParams contains parameters of the KafkaProducer.SendMessage
type KafkaProducerMockSendMessageParams struct {
	orderID int64
	status  string
}

// KafkaProducerMockSendMessageParamPtrs contains pointers to parameters of the KafkaProducer.SendMessage
type KafkaProducerMockSendMessageParamPtrs struct {
	orderID *int64
	status  *string
}

// KafkaProducerMockSendMessageOrigins contains origins of expectations of the KafkaProducer.SendMessage
type KafkaProducerMockSendMessageExpectationOrigins struct {
	origin        string
	originOrderID string
	originStatus  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSendMessage *mKafkaProducerMockSendMessage) Optional() *mKafkaProducerMockSendMessage {
	mmSendMessage.optional = true
	return mmSendMessage
}

// Expect sets up expected params for KafkaProducer.SendMessage
func (mmSendMessage *mKafkaProducerMockSendMessage) Expect(orderID int64, status string) *mKafkaProducerMockSendMessage {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("KafkaProducerMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &KafkaProducerMockSendMessageExpectation{}
	}

	if mmSendMessage.defaultExpectation.paramPtrs != nil {
		mmSendMessage.mock.t.Fatalf("KafkaProducerMock.SendMessage mock is already set by ExpectParams functions")
	}

	mmSendMessage.defaultExpectation.params = &KafkaProducerMockSendMessageParams{orderID, status}
	mmSendMessage.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSendMessage.expectations {
		if minimock.Equal(e.params, mmSendMessage.defaultExpectation.params) {
			mmSendMessage.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendMessage.defaultExpectation.params)
		}
	}

	return mmSendMessage
}

// ExpectOrderIDParam1 sets up expected param orderID for KafkaProducer.SendMessage
func (mmSendMessage *mKafkaProducerMockSendMessage) ExpectOrderIDParam1(orderID int64) *mKafkaProducerMockSendMessage {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("KafkaProducerMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &KafkaProducerMockSendMessageExpectation{}
	}

	if mmSendMessage.defaultExpectation.params != nil {
		mmSendMessage.mock.t.Fatalf("KafkaProducerMock.SendMessage mock is already set by Expect")
	}

	if mmSendMessage.defaultExpectation.paramPtrs == nil {
		mmSendMessage.defaultExpectation.paramPtrs = &KafkaProducerMockSendMessageParamPtrs{}
	}
	mmSendMessage.defaultExpectation.paramPtrs.orderID = &orderID
	mmSendMessage.defaultExpectation.expectationOrigins.originOrderID = minimock.CallerInfo(1)

	return mmSendMessage
}

// ExpectStatusParam2 sets up expected param status for KafkaProducer.SendMessage
func (mmSendMessage *mKafkaProducerMockSendMessage) ExpectStatusParam2(status string) *mKafkaProducerMockSendMessage {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("KafkaProducerMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &KafkaProducerMockSendMessageExpectation{}
	}

	if mmSendMessage.defaultExpectation.params != nil {
		mmSendMessage.mock.t.Fatalf("KafkaProducerMock.SendMessage mock is already set by Expect")
	}

	if mmSendMessage.defaultExpectation.paramPtrs == nil {
		mmSendMessage.defaultExpectation.paramPtrs = &KafkaProducerMockSendMessageParamPtrs{}
	}
	mmSendMessage.defaultExpectation.paramPtrs.status = &status
	mmSendMessage.defaultExpectation.expectationOrigins.originStatus = minimock.CallerInfo(1)

	return mmSendMessage
}

// Inspect accepts an inspector function that has same arguments as the KafkaProducer.SendMessage
func (mmSendMessage *mKafkaProducerMockSendMessage) Inspect(f func(orderID int64, status string)) *mKafkaProducerMockSendMessage {
	if mmSendMessage.mock.inspectFuncSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("Inspect function is already set for KafkaProducerMock.SendMessage")
	}

	mmSendMessage.mock.inspectFuncSendMessage = f

	return mmSendMessage
}

// Return sets up results that will be returned by KafkaProducer.SendMessage
func (mmSendMessage *mKafkaProducerMockSendMessage) Return() *KafkaProducerMock {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("KafkaProducerMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &KafkaProducerMockSendMessageExpectation{mock: mmSendMessage.mock}
	}

	mmSendMessage.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSendMessage.mock
}

// Set uses given function f to mock the KafkaProducer.SendMessage method
func (mmSendMessage *mKafkaProducerMockSendMessage) Set(f func(orderID int64, status string)) *KafkaProducerMock {
	if mmSendMessage.defaultExpectation != nil {
		mmSendMessage.mock.t.Fatalf("Default expectation is already set for the KafkaProducer.SendMessage method")
	}

	if len(mmSendMessage.expectations) > 0 {
		mmSendMessage.mock.t.Fatalf("Some expectations are already set for the KafkaProducer.SendMessage method")
	}

	mmSendMessage.mock.funcSendMessage = f
	mmSendMessage.mock.funcSendMessageOrigin = minimock.CallerInfo(1)
	return mmSendMessage.mock
}

// When sets expectation for the KafkaProducer.SendMessage which will trigger the result defined by the following
// Then helper
func (mmSendMessage *mKafkaProducerMockSendMessage) When(orderID int64, status string) *KafkaProducerMockSendMessageExpectation {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("KafkaProducerMock.SendMessage mock is already set by Set")
	}

	expectation := &KafkaProducerMockSendMessageExpectation{
		mock:               mmSendMessage.mock,
		params:             &KafkaProducerMockSendMessageParams{orderID, status},
		expectationOrigins: KafkaProducerMockSendMessageExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSendMessage.expectations = append(mmSendMessage.expectations, expectation)
	return expectation
}

// Then sets up KafkaProducer.SendMessage return parameters for the expectation previously defined by the When method

func (e *KafkaProducerMockSendMessageExpectation) Then() *KafkaProducerMock {
	return e.mock
}

// Times sets number of times KafkaProducer.SendMessage should be invoked
func (mmSendMessage *mKafkaProducerMockSendMessage) Times(n uint64) *mKafkaProducerMockSendMessage {
	if n == 0 {
		mmSendMessage.mock.t.Fatalf("Times of KafkaProducerMock.SendMessage mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSendMessage.expectedInvocations, n)
	mmSendMessage.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSendMessage
}

func (mmSendMessage *mKafkaProducerMockSendMessage) invocationsDone() bool {
	if len(mmSendMessage.expectations) == 0 && mmSendMessage.defaultExpectation == nil && mmSendMessage.mock.funcSendMessage == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSendMessage.mock.afterSendMessageCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSendMessage.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SendMessage implements mm_service.KafkaProducer
func (mmSendMessage *KafkaProducerMock) SendMessage(orderID int64, status string) {
	mm_atomic.AddUint64(&mmSendMessage.beforeSendMessageCounter, 1)
	defer mm_atomic.AddUint64(&mmSendMessage.afterSendMessageCounter, 1)

	mmSendMessage.t.Helper()

	if mmSendMessage.inspectFuncSendMessage != nil {
		mmSendMessage.inspectFuncSendMessage(orderID, status)
	}

	mm_params := KafkaProducerMockSendMessageParams{orderID, status}

	// Record call args
	mmSendMessage.SendMessageMock.mutex.Lock()
	mmSendMessage.SendMessageMock.callArgs = append(mmSendMessage.SendMessageMock.callArgs, &mm_params)
	mmSendMessage.SendMessageMock.mutex.Unlock()

	for _, e := range mmSendMessage.SendMessageMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmSendMessage.SendMessageMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendMessage.SendMessageMock.defaultExpectation.Counter, 1)
		mm_want := mmSendMessage.SendMessageMock.defaultExpectation.params
		mm_want_ptrs := mmSendMessage.SendMessageMock.defaultExpectation.paramPtrs

		mm_got := KafkaProducerMockSendMessageParams{orderID, status}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.orderID != nil && !minimock.Equal(*mm_want_ptrs.orderID, mm_got.orderID) {
				mmSendMessage.t.Errorf("KafkaProducerMock.SendMessage got unexpected parameter orderID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendMessage.SendMessageMock.defaultExpectation.expectationOrigins.originOrderID, *mm_want_ptrs.orderID, mm_got.orderID, minimock.Diff(*mm_want_ptrs.orderID, mm_got.orderID))
			}

			if mm_want_ptrs.status != nil && !minimock.Equal(*mm_want_ptrs.status, mm_got.status) {
				mmSendMessage.t.Errorf("KafkaProducerMock.SendMessage got unexpected parameter status, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendMessage.SendMessageMock.defaultExpectation.expectationOrigins.originStatus, *mm_want_ptrs.status, mm_got.status, minimock.Diff(*mm_want_ptrs.status, mm_got.status))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendMessage.t.Errorf("KafkaProducerMock.SendMessage got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSendMessage.SendMessageMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmSendMessage.funcSendMessage != nil {
		mmSendMessage.funcSendMessage(orderID, status)
		return
	}
	mmSendMessage.t.Fatalf("Unexpected call to KafkaProducerMock.SendMessage. %v %v", orderID, status)

}

// SendMessageAfterCounter returns a count of finished KafkaProducerMock.SendMessage invocations
func (mmSendMessage *KafkaProducerMock) SendMessageAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendMessage.afterSendMessageCounter)
}

// SendMessageBeforeCounter returns a count of KafkaProducerMock.SendMessage invocations
func (mmSendMessage *KafkaProducerMock) SendMessageBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendMessage.beforeSendMessageCounter)
}

// Calls returns a list of arguments used in each call to KafkaProducerMock.SendMessage.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendMessage *mKafkaProducerMockSendMessage) Calls() []*KafkaProducerMockSendMessageParams {
	mmSendMessage.mutex.RLock()

	argCopy := make([]*KafkaProducerMockSendMessageParams, len(mmSendMessage.callArgs))
	copy(argCopy, mmSendMessage.callArgs)

	mmSendMessage.mutex.RUnlock()

	return argCopy
}

// MinimockSendMessageDone returns true if the count of the SendMessage invocations corresponds
// the number of defined expectations
func (m *KafkaProducerMock) MinimockSendMessageDone() bool {
	if m.SendMessageMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendMessageMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendMessageMock.invocationsDone()
}

// MinimockSendMessageInspect logs each unmet expectation
func (m *KafkaProducerMock) MinimockSendMessageInspect() {
	for _, e := range m.SendMessageMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to KafkaProducerMock.SendMessage at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendMessageCounter := mm_atomic.LoadUint64(&m.afterSendMessageCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendMessageMock.defaultExpectation != nil && afterSendMessageCounter < 1 {
		if m.SendMessageMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to KafkaProducerMock.SendMessage at\n%s", m.SendMessageMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to KafkaProducerMock.SendMessage at\n%s with params: %#v", m.SendMessageMock.defaultExpectation.expectationOrigins.origin, *m.SendMessageMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendMessage != nil && afterSendMessageCounter < 1 {
		m.t.Errorf("Expected call to KafkaProducerMock.SendMessage at\n%s", m.funcSendMessageOrigin)
	}

	if !m.SendMessageMock.invocationsDone() && afterSendMessageCounter > 0 {
		m.t.Errorf("Expected %d calls to KafkaProducerMock.SendMessage at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendMessageMock.expectedInvocations), m.SendMessageMock.expectedInvocationsOrigin, afterSendMessageCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *KafkaProducerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSendMessageInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *KafkaProducerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *KafkaProducerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendMessageDone()
}
