// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mock

//go:generate minimock -i route256/loms/internal/domain/service/loms.OutboxService -o outbox_service_mock.go -n OutboxServiceMock -p mock

import (
	"context"
	"route256/loms/internal/domain/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// OutboxServiceMock implements mm_loms.OutboxService
type OutboxServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateMessage          func(ctx context.Context, orderID int64, status model.Status)
	funcCreateMessageOrigin    string
	inspectFuncCreateMessage   func(ctx context.Context, orderID int64, status model.Status)
	afterCreateMessageCounter  uint64
	beforeCreateMessageCounter uint64
	CreateMessageMock          mOutboxServiceMockCreateMessage
}

// NewOutboxServiceMock returns a mock for mm_loms.OutboxService
func NewOutboxServiceMock(t minimock.Tester) *OutboxServiceMock {
	m := &OutboxServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMessageMock = mOutboxServiceMockCreateMessage{mock: m}
	m.CreateMessageMock.callArgs = []*OutboxServiceMockCreateMessageParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mOutboxServiceMockCreateMessage struct {
	optional           bool
	mock               *OutboxServiceMock
	defaultExpectation *OutboxServiceMockCreateMessageExpectation
	expectations       []*OutboxServiceMockCreateMessageExpectation

	callArgs []*OutboxServiceMockCreateMessageParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// OutboxServiceMockCreateMessageExpectation specifies expectation struct of the OutboxService.CreateMessage
type OutboxServiceMockCreateMessageExpectation struct {
	mock               *OutboxServiceMock
	params             *OutboxServiceMockCreateMessageParams
	paramPtrs          *OutboxServiceMockCreateMessageParamPtrs
	expectationOrigins OutboxServiceMockCreateMessageExpectationOrigins

	returnOrigin string
	Counter      uint64
}

// OutboxServiceMockCreateMessageParams contains parameters of the OutboxService.CreateMessage
type OutboxServiceMockCreateMessageParams struct {
	ctx     context.Context
	orderID int64
	status  model.Status
}

// OutboxServiceMockCreateMessageParamPtrs contains pointers to parameters of the OutboxService.CreateMessage
type OutboxServiceMockCreateMessageParamPtrs struct {
	ctx     *context.Context
	orderID *int64
	status  *model.Status
}

// OutboxServiceMockCreateMessageOrigins contains origins of expectations of the OutboxService.CreateMessage
type OutboxServiceMockCreateMessageExpectationOrigins struct {
	origin        string
	originCtx     string
	originOrderID string
	originStatus  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateMessage *mOutboxServiceMockCreateMessage) Optional() *mOutboxServiceMockCreateMessage {
	mmCreateMessage.optional = true
	return mmCreateMessage
}

// Expect sets up expected params for OutboxService.CreateMessage
func (mmCreateMessage *mOutboxServiceMockCreateMessage) Expect(ctx context.Context, orderID int64, status model.Status) *mOutboxServiceMockCreateMessage {
	if mmCreateMessage.mock.funcCreateMessage != nil {
		mmCreateMessage.mock.t.Fatalf("OutboxServiceMock.CreateMessage mock is already set by Set")
	}

	if mmCreateMessage.defaultExpectation == nil {
		mmCreateMessage.defaultExpectation = &OutboxServiceMockCreateMessageExpectation{}
	}

	if mmCreateMessage.defaultExpectation.paramPtrs != nil {
		mmCreateMessage.mock.t.Fatalf("OutboxServiceMock.CreateMessage mock is already set by ExpectParams functions")
	}

	mmCreateMessage.defaultExpectation.params = &OutboxServiceMockCreateMessageParams{ctx, orderID, status}
	mmCreateMessage.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateMessage.expectations {
		if minimock.Equal(e.params, mmCreateMessage.defaultExpectation.params) {
			mmCreateMessage.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateMessage.defaultExpectation.params)
		}
	}

	return mmCreateMessage
}

// ExpectCtxParam1 sets up expected param ctx for OutboxService.CreateMessage
func (mmCreateMessage *mOutboxServiceMockCreateMessage) ExpectCtxParam1(ctx context.Context) *mOutboxServiceMockCreateMessage {
	if mmCreateMessage.mock.funcCreateMessage != nil {
		mmCreateMessage.mock.t.Fatalf("OutboxServiceMock.CreateMessage mock is already set by Set")
	}

	if mmCreateMessage.defaultExpectation == nil {
		mmCreateMessage.defaultExpectation = &OutboxServiceMockCreateMessageExpectation{}
	}

	if mmCreateMessage.defaultExpectation.params != nil {
		mmCreateMessage.mock.t.Fatalf("OutboxServiceMock.CreateMessage mock is already set by Expect")
	}

	if mmCreateMessage.defaultExpectation.paramPtrs == nil {
		mmCreateMessage.defaultExpectation.paramPtrs = &OutboxServiceMockCreateMessageParamPtrs{}
	}
	mmCreateMessage.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateMessage.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateMessage
}

// ExpectOrderIDParam2 sets up expected param orderID for OutboxService.CreateMessage
func (mmCreateMessage *mOutboxServiceMockCreateMessage) ExpectOrderIDParam2(orderID int64) *mOutboxServiceMockCreateMessage {
	if mmCreateMessage.mock.funcCreateMessage != nil {
		mmCreateMessage.mock.t.Fatalf("OutboxServiceMock.CreateMessage mock is already set by Set")
	}

	if mmCreateMessage.defaultExpectation == nil {
		mmCreateMessage.defaultExpectation = &OutboxServiceMockCreateMessageExpectation{}
	}

	if mmCreateMessage.defaultExpectation.params != nil {
		mmCreateMessage.mock.t.Fatalf("OutboxServiceMock.CreateMessage mock is already set by Expect")
	}

	if mmCreateMessage.defaultExpectation.paramPtrs == nil {
		mmCreateMessage.defaultExpectation.paramPtrs = &OutboxServiceMockCreateMessageParamPtrs{}
	}
	mmCreateMessage.defaultExpectation.paramPtrs.orderID = &orderID
	mmCreateMessage.defaultExpectation.expectationOrigins.originOrderID = minimock.CallerInfo(1)

	return mmCreateMessage
}

// ExpectStatusParam3 sets up expected param status for OutboxService.CreateMessage
func (mmCreateMessage *mOutboxServiceMockCreateMessage) ExpectStatusParam3(status model.Status) *mOutboxServiceMockCreateMessage {
	if mmCreateMessage.mock.funcCreateMessage != nil {
		mmCreateMessage.mock.t.Fatalf("OutboxServiceMock.CreateMessage mock is already set by Set")
	}

	if mmCreateMessage.defaultExpectation == nil {
		mmCreateMessage.defaultExpectation = &OutboxServiceMockCreateMessageExpectation{}
	}

	if mmCreateMessage.defaultExpectation.params != nil {
		mmCreateMessage.mock.t.Fatalf("OutboxServiceMock.CreateMessage mock is already set by Expect")
	}

	if mmCreateMessage.defaultExpectation.paramPtrs == nil {
		mmCreateMessage.defaultExpectation.paramPtrs = &OutboxServiceMockCreateMessageParamPtrs{}
	}
	mmCreateMessage.defaultExpectation.paramPtrs.status = &status
	mmCreateMessage.defaultExpectation.expectationOrigins.originStatus = minimock.CallerInfo(1)

	return mmCreateMessage
}

// Inspect accepts an inspector function that has same arguments as the OutboxService.CreateMessage
func (mmCreateMessage *mOutboxServiceMockCreateMessage) Inspect(f func(ctx context.Context, orderID int64, status model.Status)) *mOutboxServiceMockCreateMessage {
	if mmCreateMessage.mock.inspectFuncCreateMessage != nil {
		mmCreateMessage.mock.t.Fatalf("Inspect function is already set for OutboxServiceMock.CreateMessage")
	}

	mmCreateMessage.mock.inspectFuncCreateMessage = f

	return mmCreateMessage
}

// Return sets up results that will be returned by OutboxService.CreateMessage
func (mmCreateMessage *mOutboxServiceMockCreateMessage) Return() *OutboxServiceMock {
	if mmCreateMessage.mock.funcCreateMessage != nil {
		mmCreateMessage.mock.t.Fatalf("OutboxServiceMock.CreateMessage mock is already set by Set")
	}

	if mmCreateMessage.defaultExpectation == nil {
		mmCreateMessage.defaultExpectation = &OutboxServiceMockCreateMessageExpectation{mock: mmCreateMessage.mock}
	}

	mmCreateMessage.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateMessage.mock
}

// Set uses given function f to mock the OutboxService.CreateMessage method
func (mmCreateMessage *mOutboxServiceMockCreateMessage) Set(f func(ctx context.Context, orderID int64, status model.Status)) *OutboxServiceMock {
	if mmCreateMessage.defaultExpectation != nil {
		mmCreateMessage.mock.t.Fatalf("Default expectation is already set for the OutboxService.CreateMessage method")
	}

	if len(mmCreateMessage.expectations) > 0 {
		mmCreateMessage.mock.t.Fatalf("Some expectations are already set for the OutboxService.CreateMessage method")
	}

	mmCreateMessage.mock.funcCreateMessage = f
	mmCreateMessage.mock.funcCreateMessageOrigin = minimock.CallerInfo(1)
	return mmCreateMessage.mock
}

// When sets expectation for the OutboxService.CreateMessage which will trigger the result defined by the following
// Then helper
func (mmCreateMessage *mOutboxServiceMockCreateMessage) When(ctx context.Context, orderID int64, status model.Status) *OutboxServiceMockCreateMessageExpectation {
	if mmCreateMessage.mock.funcCreateMessage != nil {
		mmCreateMessage.mock.t.Fatalf("OutboxServiceMock.CreateMessage mock is already set by Set")
	}

	expectation := &OutboxServiceMockCreateMessageExpectation{
		mock:               mmCreateMessage.mock,
		params:             &OutboxServiceMockCreateMessageParams{ctx, orderID, status},
		expectationOrigins: OutboxServiceMockCreateMessageExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateMessage.expectations = append(mmCreateMessage.expectations, expectation)
	return expectation
}

// Then sets up OutboxService.CreateMessage return parameters for the expectation previously defined by the When method

func (e *OutboxServiceMockCreateMessageExpectation) Then() *OutboxServiceMock {
	return e.mock
}

// Times sets number of times OutboxService.CreateMessage should be invoked
func (mmCreateMessage *mOutboxServiceMockCreateMessage) Times(n uint64) *mOutboxServiceMockCreateMessage {
	if n == 0 {
		mmCreateMessage.mock.t.Fatalf("Times of OutboxServiceMock.CreateMessage mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateMessage.expectedInvocations, n)
	mmCreateMessage.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateMessage
}

func (mmCreateMessage *mOutboxServiceMockCreateMessage) invocationsDone() bool {
	if len(mmCreateMessage.expectations) == 0 && mmCreateMessage.defaultExpectation == nil && mmCreateMessage.mock.funcCreateMessage == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateMessage.mock.afterCreateMessageCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateMessage.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateMessage implements mm_loms.OutboxService
func (mmCreateMessage *OutboxServiceMock) CreateMessage(ctx context.Context, orderID int64, status model.Status) {
	mm_atomic.AddUint64(&mmCreateMessage.beforeCreateMessageCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateMessage.afterCreateMessageCounter, 1)

	mmCreateMessage.t.Helper()

	if mmCreateMessage.inspectFuncCreateMessage != nil {
		mmCreateMessage.inspectFuncCreateMessage(ctx, orderID, status)
	}

	mm_params := OutboxServiceMockCreateMessageParams{ctx, orderID, status}

	// Record call args
	mmCreateMessage.CreateMessageMock.mutex.Lock()
	mmCreateMessage.CreateMessageMock.callArgs = append(mmCreateMessage.CreateMessageMock.callArgs, &mm_params)
	mmCreateMessage.CreateMessageMock.mutex.Unlock()

	for _, e := range mmCreateMessage.CreateMessageMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return
		}
	}

	if mmCreateMessage.CreateMessageMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateMessage.CreateMessageMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateMessage.CreateMessageMock.defaultExpectation.params
		mm_want_ptrs := mmCreateMessage.CreateMessageMock.defaultExpectation.paramPtrs

		mm_got := OutboxServiceMockCreateMessageParams{ctx, orderID, status}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateMessage.t.Errorf("OutboxServiceMock.CreateMessage got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateMessage.CreateMessageMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.orderID != nil && !minimock.Equal(*mm_want_ptrs.orderID, mm_got.orderID) {
				mmCreateMessage.t.Errorf("OutboxServiceMock.CreateMessage got unexpected parameter orderID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateMessage.CreateMessageMock.defaultExpectation.expectationOrigins.originOrderID, *mm_want_ptrs.orderID, mm_got.orderID, minimock.Diff(*mm_want_ptrs.orderID, mm_got.orderID))
			}

			if mm_want_ptrs.status != nil && !minimock.Equal(*mm_want_ptrs.status, mm_got.status) {
				mmCreateMessage.t.Errorf("OutboxServiceMock.CreateMessage got unexpected parameter status, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateMessage.CreateMessageMock.defaultExpectation.expectationOrigins.originStatus, *mm_want_ptrs.status, mm_got.status, minimock.Diff(*mm_want_ptrs.status, mm_got.status))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateMessage.t.Errorf("OutboxServiceMock.CreateMessage got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateMessage.CreateMessageMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		return

	}
	if mmCreateMessage.funcCreateMessage != nil {
		mmCreateMessage.funcCreateMessage(ctx, orderID, status)
		return
	}
	mmCreateMessage.t.Fatalf("Unexpected call to OutboxServiceMock.CreateMessage. %v %v %v", ctx, orderID, status)

}

// CreateMessageAfterCounter returns a count of finished OutboxServiceMock.CreateMessage invocations
func (mmCreateMessage *OutboxServiceMock) CreateMessageAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateMessage.afterCreateMessageCounter)
}

// CreateMessageBeforeCounter returns a count of OutboxServiceMock.CreateMessage invocations
func (mmCreateMessage *OutboxServiceMock) CreateMessageBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateMessage.beforeCreateMessageCounter)
}

// Calls returns a list of arguments used in each call to OutboxServiceMock.CreateMessage.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateMessage *mOutboxServiceMockCreateMessage) Calls() []*OutboxServiceMockCreateMessageParams {
	mmCreateMessage.mutex.RLock()

	argCopy := make([]*OutboxServiceMockCreateMessageParams, len(mmCreateMessage.callArgs))
	copy(argCopy, mmCreateMessage.callArgs)

	mmCreateMessage.mutex.RUnlock()

	return argCopy
}

// MinimockCreateMessageDone returns true if the count of the CreateMessage invocations corresponds
// the number of defined expectations
func (m *OutboxServiceMock) MinimockCreateMessageDone() bool {
	if m.CreateMessageMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateMessageMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateMessageMock.invocationsDone()
}

// MinimockCreateMessageInspect logs each unmet expectation
func (m *OutboxServiceMock) MinimockCreateMessageInspect() {
	for _, e := range m.CreateMessageMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to OutboxServiceMock.CreateMessage at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateMessageCounter := mm_atomic.LoadUint64(&m.afterCreateMessageCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMessageMock.defaultExpectation != nil && afterCreateMessageCounter < 1 {
		if m.CreateMessageMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to OutboxServiceMock.CreateMessage at\n%s", m.CreateMessageMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to OutboxServiceMock.CreateMessage at\n%s with params: %#v", m.CreateMessageMock.defaultExpectation.expectationOrigins.origin, *m.CreateMessageMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateMessage != nil && afterCreateMessageCounter < 1 {
		m.t.Errorf("Expected call to OutboxServiceMock.CreateMessage at\n%s", m.funcCreateMessageOrigin)
	}

	if !m.CreateMessageMock.invocationsDone() && afterCreateMessageCounter > 0 {
		m.t.Errorf("Expected %d calls to OutboxServiceMock.CreateMessage at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateMessageMock.expectedInvocations), m.CreateMessageMock.expectedInvocationsOrigin, afterCreateMessageCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *OutboxServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateMessageInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *OutboxServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *OutboxServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateMessageDone()
}
