// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mock

//go:generate minimock -i route256/loms/internal/domain/service/loms.PgPooler -o pg_pooler_mock.go -n PgPoolerMock -p mock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// PgPoolerMock implements mm_loms.PgPooler
type PgPoolerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcInTx          func(ctx context.Context, fn func(ctx context.Context) error) (err error)
	funcInTxOrigin    string
	inspectFuncInTx   func(ctx context.Context, fn func(ctx context.Context) error)
	afterInTxCounter  uint64
	beforeInTxCounter uint64
	InTxMock          mPgPoolerMockInTx
}

// NewPgPoolerMock returns a mock for mm_loms.PgPooler
func NewPgPoolerMock(t minimock.Tester) *PgPoolerMock {
	m := &PgPoolerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.InTxMock = mPgPoolerMockInTx{mock: m}
	m.InTxMock.callArgs = []*PgPoolerMockInTxParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mPgPoolerMockInTx struct {
	optional           bool
	mock               *PgPoolerMock
	defaultExpectation *PgPoolerMockInTxExpectation
	expectations       []*PgPoolerMockInTxExpectation

	callArgs []*PgPoolerMockInTxParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// PgPoolerMockInTxExpectation specifies expectation struct of the PgPooler.InTx
type PgPoolerMockInTxExpectation struct {
	mock               *PgPoolerMock
	params             *PgPoolerMockInTxParams
	paramPtrs          *PgPoolerMockInTxParamPtrs
	expectationOrigins PgPoolerMockInTxExpectationOrigins
	results            *PgPoolerMockInTxResults
	returnOrigin       string
	Counter            uint64
}

// PgPoolerMockInTxParams contains parameters of the PgPooler.InTx
type PgPoolerMockInTxParams struct {
	ctx context.Context
	fn  func(ctx context.Context) error
}

// PgPoolerMockInTxParamPtrs contains pointers to parameters of the PgPooler.InTx
type PgPoolerMockInTxParamPtrs struct {
	ctx *context.Context
	fn  *func(ctx context.Context) error
}

// PgPoolerMockInTxResults contains results of the PgPooler.InTx
type PgPoolerMockInTxResults struct {
	err error
}

// PgPoolerMockInTxOrigins contains origins of expectations of the PgPooler.InTx
type PgPoolerMockInTxExpectationOrigins struct {
	origin    string
	originCtx string
	originFn  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmInTx *mPgPoolerMockInTx) Optional() *mPgPoolerMockInTx {
	mmInTx.optional = true
	return mmInTx
}

// Expect sets up expected params for PgPooler.InTx
func (mmInTx *mPgPoolerMockInTx) Expect(ctx context.Context, fn func(ctx context.Context) error) *mPgPoolerMockInTx {
	if mmInTx.mock.funcInTx != nil {
		mmInTx.mock.t.Fatalf("PgPoolerMock.InTx mock is already set by Set")
	}

	if mmInTx.defaultExpectation == nil {
		mmInTx.defaultExpectation = &PgPoolerMockInTxExpectation{}
	}

	if mmInTx.defaultExpectation.paramPtrs != nil {
		mmInTx.mock.t.Fatalf("PgPoolerMock.InTx mock is already set by ExpectParams functions")
	}

	mmInTx.defaultExpectation.params = &PgPoolerMockInTxParams{ctx, fn}
	mmInTx.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmInTx.expectations {
		if minimock.Equal(e.params, mmInTx.defaultExpectation.params) {
			mmInTx.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmInTx.defaultExpectation.params)
		}
	}

	return mmInTx
}

// ExpectCtxParam1 sets up expected param ctx for PgPooler.InTx
func (mmInTx *mPgPoolerMockInTx) ExpectCtxParam1(ctx context.Context) *mPgPoolerMockInTx {
	if mmInTx.mock.funcInTx != nil {
		mmInTx.mock.t.Fatalf("PgPoolerMock.InTx mock is already set by Set")
	}

	if mmInTx.defaultExpectation == nil {
		mmInTx.defaultExpectation = &PgPoolerMockInTxExpectation{}
	}

	if mmInTx.defaultExpectation.params != nil {
		mmInTx.mock.t.Fatalf("PgPoolerMock.InTx mock is already set by Expect")
	}

	if mmInTx.defaultExpectation.paramPtrs == nil {
		mmInTx.defaultExpectation.paramPtrs = &PgPoolerMockInTxParamPtrs{}
	}
	mmInTx.defaultExpectation.paramPtrs.ctx = &ctx
	mmInTx.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmInTx
}

// ExpectFnParam2 sets up expected param fn for PgPooler.InTx
func (mmInTx *mPgPoolerMockInTx) ExpectFnParam2(fn func(ctx context.Context) error) *mPgPoolerMockInTx {
	if mmInTx.mock.funcInTx != nil {
		mmInTx.mock.t.Fatalf("PgPoolerMock.InTx mock is already set by Set")
	}

	if mmInTx.defaultExpectation == nil {
		mmInTx.defaultExpectation = &PgPoolerMockInTxExpectation{}
	}

	if mmInTx.defaultExpectation.params != nil {
		mmInTx.mock.t.Fatalf("PgPoolerMock.InTx mock is already set by Expect")
	}

	if mmInTx.defaultExpectation.paramPtrs == nil {
		mmInTx.defaultExpectation.paramPtrs = &PgPoolerMockInTxParamPtrs{}
	}
	mmInTx.defaultExpectation.paramPtrs.fn = &fn
	mmInTx.defaultExpectation.expectationOrigins.originFn = minimock.CallerInfo(1)

	return mmInTx
}

// Inspect accepts an inspector function that has same arguments as the PgPooler.InTx
func (mmInTx *mPgPoolerMockInTx) Inspect(f func(ctx context.Context, fn func(ctx context.Context) error)) *mPgPoolerMockInTx {
	if mmInTx.mock.inspectFuncInTx != nil {
		mmInTx.mock.t.Fatalf("Inspect function is already set for PgPoolerMock.InTx")
	}

	mmInTx.mock.inspectFuncInTx = f

	return mmInTx
}

// Return sets up results that will be returned by PgPooler.InTx
func (mmInTx *mPgPoolerMockInTx) Return(err error) *PgPoolerMock {
	if mmInTx.mock.funcInTx != nil {
		mmInTx.mock.t.Fatalf("PgPoolerMock.InTx mock is already set by Set")
	}

	if mmInTx.defaultExpectation == nil {
		mmInTx.defaultExpectation = &PgPoolerMockInTxExpectation{mock: mmInTx.mock}
	}
	mmInTx.defaultExpectation.results = &PgPoolerMockInTxResults{err}
	mmInTx.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmInTx.mock
}

// Set uses given function f to mock the PgPooler.InTx method
func (mmInTx *mPgPoolerMockInTx) Set(f func(ctx context.Context, fn func(ctx context.Context) error) (err error)) *PgPoolerMock {
	if mmInTx.defaultExpectation != nil {
		mmInTx.mock.t.Fatalf("Default expectation is already set for the PgPooler.InTx method")
	}

	if len(mmInTx.expectations) > 0 {
		mmInTx.mock.t.Fatalf("Some expectations are already set for the PgPooler.InTx method")
	}

	mmInTx.mock.funcInTx = f
	mmInTx.mock.funcInTxOrigin = minimock.CallerInfo(1)
	return mmInTx.mock
}

// When sets expectation for the PgPooler.InTx which will trigger the result defined by the following
// Then helper
func (mmInTx *mPgPoolerMockInTx) When(ctx context.Context, fn func(ctx context.Context) error) *PgPoolerMockInTxExpectation {
	if mmInTx.mock.funcInTx != nil {
		mmInTx.mock.t.Fatalf("PgPoolerMock.InTx mock is already set by Set")
	}

	expectation := &PgPoolerMockInTxExpectation{
		mock:               mmInTx.mock,
		params:             &PgPoolerMockInTxParams{ctx, fn},
		expectationOrigins: PgPoolerMockInTxExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmInTx.expectations = append(mmInTx.expectations, expectation)
	return expectation
}

// Then sets up PgPooler.InTx return parameters for the expectation previously defined by the When method
func (e *PgPoolerMockInTxExpectation) Then(err error) *PgPoolerMock {
	e.results = &PgPoolerMockInTxResults{err}
	return e.mock
}

// Times sets number of times PgPooler.InTx should be invoked
func (mmInTx *mPgPoolerMockInTx) Times(n uint64) *mPgPoolerMockInTx {
	if n == 0 {
		mmInTx.mock.t.Fatalf("Times of PgPoolerMock.InTx mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmInTx.expectedInvocations, n)
	mmInTx.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmInTx
}

func (mmInTx *mPgPoolerMockInTx) invocationsDone() bool {
	if len(mmInTx.expectations) == 0 && mmInTx.defaultExpectation == nil && mmInTx.mock.funcInTx == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmInTx.mock.afterInTxCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmInTx.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// InTx implements mm_loms.PgPooler
func (mmInTx *PgPoolerMock) InTx(ctx context.Context, fn func(ctx context.Context) error) (err error) {
	mm_atomic.AddUint64(&mmInTx.beforeInTxCounter, 1)
	defer mm_atomic.AddUint64(&mmInTx.afterInTxCounter, 1)

	mmInTx.t.Helper()

	if mmInTx.inspectFuncInTx != nil {
		mmInTx.inspectFuncInTx(ctx, fn)
	}

	mm_params := PgPoolerMockInTxParams{ctx, fn}

	// Record call args
	mmInTx.InTxMock.mutex.Lock()
	mmInTx.InTxMock.callArgs = append(mmInTx.InTxMock.callArgs, &mm_params)
	mmInTx.InTxMock.mutex.Unlock()

	for _, e := range mmInTx.InTxMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmInTx.InTxMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmInTx.InTxMock.defaultExpectation.Counter, 1)
		mm_want := mmInTx.InTxMock.defaultExpectation.params
		mm_want_ptrs := mmInTx.InTxMock.defaultExpectation.paramPtrs

		mm_got := PgPoolerMockInTxParams{ctx, fn}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmInTx.t.Errorf("PgPoolerMock.InTx got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInTx.InTxMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.fn != nil && !minimock.Equal(*mm_want_ptrs.fn, mm_got.fn) {
				mmInTx.t.Errorf("PgPoolerMock.InTx got unexpected parameter fn, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmInTx.InTxMock.defaultExpectation.expectationOrigins.originFn, *mm_want_ptrs.fn, mm_got.fn, minimock.Diff(*mm_want_ptrs.fn, mm_got.fn))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmInTx.t.Errorf("PgPoolerMock.InTx got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmInTx.InTxMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmInTx.InTxMock.defaultExpectation.results
		if mm_results == nil {
			mmInTx.t.Fatal("No results are set for the PgPoolerMock.InTx")
		}
		return (*mm_results).err
	}
	if mmInTx.funcInTx != nil {
		return mmInTx.funcInTx(ctx, fn)
	}
	mmInTx.t.Fatalf("Unexpected call to PgPoolerMock.InTx. %v %v", ctx, fn)
	return
}

// InTxAfterCounter returns a count of finished PgPoolerMock.InTx invocations
func (mmInTx *PgPoolerMock) InTxAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInTx.afterInTxCounter)
}

// InTxBeforeCounter returns a count of PgPoolerMock.InTx invocations
func (mmInTx *PgPoolerMock) InTxBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmInTx.beforeInTxCounter)
}

// Calls returns a list of arguments used in each call to PgPoolerMock.InTx.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmInTx *mPgPoolerMockInTx) Calls() []*PgPoolerMockInTxParams {
	mmInTx.mutex.RLock()

	argCopy := make([]*PgPoolerMockInTxParams, len(mmInTx.callArgs))
	copy(argCopy, mmInTx.callArgs)

	mmInTx.mutex.RUnlock()

	return argCopy
}

// MinimockInTxDone returns true if the count of the InTx invocations corresponds
// the number of defined expectations
func (m *PgPoolerMock) MinimockInTxDone() bool {
	if m.InTxMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.InTxMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.InTxMock.invocationsDone()
}

// MinimockInTxInspect logs each unmet expectation
func (m *PgPoolerMock) MinimockInTxInspect() {
	for _, e := range m.InTxMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to PgPoolerMock.InTx at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterInTxCounter := mm_atomic.LoadUint64(&m.afterInTxCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.InTxMock.defaultExpectation != nil && afterInTxCounter < 1 {
		if m.InTxMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to PgPoolerMock.InTx at\n%s", m.InTxMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to PgPoolerMock.InTx at\n%s with params: %#v", m.InTxMock.defaultExpectation.expectationOrigins.origin, *m.InTxMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcInTx != nil && afterInTxCounter < 1 {
		m.t.Errorf("Expected call to PgPoolerMock.InTx at\n%s", m.funcInTxOrigin)
	}

	if !m.InTxMock.invocationsDone() && afterInTxCounter > 0 {
		m.t.Errorf("Expected %d calls to PgPoolerMock.InTx at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.InTxMock.expectedInvocations), m.InTxMock.expectedInvocationsOrigin, afterInTxCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *PgPoolerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockInTxInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *PgPoolerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *PgPoolerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockInTxDone()
}
