// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mock

//go:generate minimock -i route256/cart/internal/domain/service.LomsService -o loms_service.go -n LomsServiceMock -p mock

import (
	"context"
	"route256/cart/internal/domain/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// LomsServiceMock implements mm_service.LomsService
type LomsServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcOrderCreate          func(ctx context.Context, userID model.UserID, reportCart *model.ReportCart) (i1 int64, err error)
	funcOrderCreateOrigin    string
	inspectFuncOrderCreate   func(ctx context.Context, userID model.UserID, reportCart *model.ReportCart)
	afterOrderCreateCounter  uint64
	beforeOrderCreateCounter uint64
	OrderCreateMock          mLomsServiceMockOrderCreate

	funcStockInfo          func(ctx context.Context, sku model.Sku) (u1 uint32, err error)
	funcStockInfoOrigin    string
	inspectFuncStockInfo   func(ctx context.Context, sku model.Sku)
	afterStockInfoCounter  uint64
	beforeStockInfoCounter uint64
	StockInfoMock          mLomsServiceMockStockInfo
}

// NewLomsServiceMock returns a mock for mm_service.LomsService
func NewLomsServiceMock(t minimock.Tester) *LomsServiceMock {
	m := &LomsServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.OrderCreateMock = mLomsServiceMockOrderCreate{mock: m}
	m.OrderCreateMock.callArgs = []*LomsServiceMockOrderCreateParams{}

	m.StockInfoMock = mLomsServiceMockStockInfo{mock: m}
	m.StockInfoMock.callArgs = []*LomsServiceMockStockInfoParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mLomsServiceMockOrderCreate struct {
	optional           bool
	mock               *LomsServiceMock
	defaultExpectation *LomsServiceMockOrderCreateExpectation
	expectations       []*LomsServiceMockOrderCreateExpectation

	callArgs []*LomsServiceMockOrderCreateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsServiceMockOrderCreateExpectation specifies expectation struct of the LomsService.OrderCreate
type LomsServiceMockOrderCreateExpectation struct {
	mock               *LomsServiceMock
	params             *LomsServiceMockOrderCreateParams
	paramPtrs          *LomsServiceMockOrderCreateParamPtrs
	expectationOrigins LomsServiceMockOrderCreateExpectationOrigins
	results            *LomsServiceMockOrderCreateResults
	returnOrigin       string
	Counter            uint64
}

// LomsServiceMockOrderCreateParams contains parameters of the LomsService.OrderCreate
type LomsServiceMockOrderCreateParams struct {
	ctx        context.Context
	userID     model.UserID
	reportCart *model.ReportCart
}

// LomsServiceMockOrderCreateParamPtrs contains pointers to parameters of the LomsService.OrderCreate
type LomsServiceMockOrderCreateParamPtrs struct {
	ctx        *context.Context
	userID     *model.UserID
	reportCart **model.ReportCart
}

// LomsServiceMockOrderCreateResults contains results of the LomsService.OrderCreate
type LomsServiceMockOrderCreateResults struct {
	i1  int64
	err error
}

// LomsServiceMockOrderCreateOrigins contains origins of expectations of the LomsService.OrderCreate
type LomsServiceMockOrderCreateExpectationOrigins struct {
	origin           string
	originCtx        string
	originUserID     string
	originReportCart string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmOrderCreate *mLomsServiceMockOrderCreate) Optional() *mLomsServiceMockOrderCreate {
	mmOrderCreate.optional = true
	return mmOrderCreate
}

// Expect sets up expected params for LomsService.OrderCreate
func (mmOrderCreate *mLomsServiceMockOrderCreate) Expect(ctx context.Context, userID model.UserID, reportCart *model.ReportCart) *mLomsServiceMockOrderCreate {
	if mmOrderCreate.mock.funcOrderCreate != nil {
		mmOrderCreate.mock.t.Fatalf("LomsServiceMock.OrderCreate mock is already set by Set")
	}

	if mmOrderCreate.defaultExpectation == nil {
		mmOrderCreate.defaultExpectation = &LomsServiceMockOrderCreateExpectation{}
	}

	if mmOrderCreate.defaultExpectation.paramPtrs != nil {
		mmOrderCreate.mock.t.Fatalf("LomsServiceMock.OrderCreate mock is already set by ExpectParams functions")
	}

	mmOrderCreate.defaultExpectation.params = &LomsServiceMockOrderCreateParams{ctx, userID, reportCart}
	mmOrderCreate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmOrderCreate.expectations {
		if minimock.Equal(e.params, mmOrderCreate.defaultExpectation.params) {
			mmOrderCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmOrderCreate.defaultExpectation.params)
		}
	}

	return mmOrderCreate
}

// ExpectCtxParam1 sets up expected param ctx for LomsService.OrderCreate
func (mmOrderCreate *mLomsServiceMockOrderCreate) ExpectCtxParam1(ctx context.Context) *mLomsServiceMockOrderCreate {
	if mmOrderCreate.mock.funcOrderCreate != nil {
		mmOrderCreate.mock.t.Fatalf("LomsServiceMock.OrderCreate mock is already set by Set")
	}

	if mmOrderCreate.defaultExpectation == nil {
		mmOrderCreate.defaultExpectation = &LomsServiceMockOrderCreateExpectation{}
	}

	if mmOrderCreate.defaultExpectation.params != nil {
		mmOrderCreate.mock.t.Fatalf("LomsServiceMock.OrderCreate mock is already set by Expect")
	}

	if mmOrderCreate.defaultExpectation.paramPtrs == nil {
		mmOrderCreate.defaultExpectation.paramPtrs = &LomsServiceMockOrderCreateParamPtrs{}
	}
	mmOrderCreate.defaultExpectation.paramPtrs.ctx = &ctx
	mmOrderCreate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmOrderCreate
}

// ExpectUserIDParam2 sets up expected param userID for LomsService.OrderCreate
func (mmOrderCreate *mLomsServiceMockOrderCreate) ExpectUserIDParam2(userID model.UserID) *mLomsServiceMockOrderCreate {
	if mmOrderCreate.mock.funcOrderCreate != nil {
		mmOrderCreate.mock.t.Fatalf("LomsServiceMock.OrderCreate mock is already set by Set")
	}

	if mmOrderCreate.defaultExpectation == nil {
		mmOrderCreate.defaultExpectation = &LomsServiceMockOrderCreateExpectation{}
	}

	if mmOrderCreate.defaultExpectation.params != nil {
		mmOrderCreate.mock.t.Fatalf("LomsServiceMock.OrderCreate mock is already set by Expect")
	}

	if mmOrderCreate.defaultExpectation.paramPtrs == nil {
		mmOrderCreate.defaultExpectation.paramPtrs = &LomsServiceMockOrderCreateParamPtrs{}
	}
	mmOrderCreate.defaultExpectation.paramPtrs.userID = &userID
	mmOrderCreate.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmOrderCreate
}

// ExpectReportCartParam3 sets up expected param reportCart for LomsService.OrderCreate
func (mmOrderCreate *mLomsServiceMockOrderCreate) ExpectReportCartParam3(reportCart *model.ReportCart) *mLomsServiceMockOrderCreate {
	if mmOrderCreate.mock.funcOrderCreate != nil {
		mmOrderCreate.mock.t.Fatalf("LomsServiceMock.OrderCreate mock is already set by Set")
	}

	if mmOrderCreate.defaultExpectation == nil {
		mmOrderCreate.defaultExpectation = &LomsServiceMockOrderCreateExpectation{}
	}

	if mmOrderCreate.defaultExpectation.params != nil {
		mmOrderCreate.mock.t.Fatalf("LomsServiceMock.OrderCreate mock is already set by Expect")
	}

	if mmOrderCreate.defaultExpectation.paramPtrs == nil {
		mmOrderCreate.defaultExpectation.paramPtrs = &LomsServiceMockOrderCreateParamPtrs{}
	}
	mmOrderCreate.defaultExpectation.paramPtrs.reportCart = &reportCart
	mmOrderCreate.defaultExpectation.expectationOrigins.originReportCart = minimock.CallerInfo(1)

	return mmOrderCreate
}

// Inspect accepts an inspector function that has same arguments as the LomsService.OrderCreate
func (mmOrderCreate *mLomsServiceMockOrderCreate) Inspect(f func(ctx context.Context, userID model.UserID, reportCart *model.ReportCart)) *mLomsServiceMockOrderCreate {
	if mmOrderCreate.mock.inspectFuncOrderCreate != nil {
		mmOrderCreate.mock.t.Fatalf("Inspect function is already set for LomsServiceMock.OrderCreate")
	}

	mmOrderCreate.mock.inspectFuncOrderCreate = f

	return mmOrderCreate
}

// Return sets up results that will be returned by LomsService.OrderCreate
func (mmOrderCreate *mLomsServiceMockOrderCreate) Return(i1 int64, err error) *LomsServiceMock {
	if mmOrderCreate.mock.funcOrderCreate != nil {
		mmOrderCreate.mock.t.Fatalf("LomsServiceMock.OrderCreate mock is already set by Set")
	}

	if mmOrderCreate.defaultExpectation == nil {
		mmOrderCreate.defaultExpectation = &LomsServiceMockOrderCreateExpectation{mock: mmOrderCreate.mock}
	}
	mmOrderCreate.defaultExpectation.results = &LomsServiceMockOrderCreateResults{i1, err}
	mmOrderCreate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmOrderCreate.mock
}

// Set uses given function f to mock the LomsService.OrderCreate method
func (mmOrderCreate *mLomsServiceMockOrderCreate) Set(f func(ctx context.Context, userID model.UserID, reportCart *model.ReportCart) (i1 int64, err error)) *LomsServiceMock {
	if mmOrderCreate.defaultExpectation != nil {
		mmOrderCreate.mock.t.Fatalf("Default expectation is already set for the LomsService.OrderCreate method")
	}

	if len(mmOrderCreate.expectations) > 0 {
		mmOrderCreate.mock.t.Fatalf("Some expectations are already set for the LomsService.OrderCreate method")
	}

	mmOrderCreate.mock.funcOrderCreate = f
	mmOrderCreate.mock.funcOrderCreateOrigin = minimock.CallerInfo(1)
	return mmOrderCreate.mock
}

// When sets expectation for the LomsService.OrderCreate which will trigger the result defined by the following
// Then helper
func (mmOrderCreate *mLomsServiceMockOrderCreate) When(ctx context.Context, userID model.UserID, reportCart *model.ReportCart) *LomsServiceMockOrderCreateExpectation {
	if mmOrderCreate.mock.funcOrderCreate != nil {
		mmOrderCreate.mock.t.Fatalf("LomsServiceMock.OrderCreate mock is already set by Set")
	}

	expectation := &LomsServiceMockOrderCreateExpectation{
		mock:               mmOrderCreate.mock,
		params:             &LomsServiceMockOrderCreateParams{ctx, userID, reportCart},
		expectationOrigins: LomsServiceMockOrderCreateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmOrderCreate.expectations = append(mmOrderCreate.expectations, expectation)
	return expectation
}

// Then sets up LomsService.OrderCreate return parameters for the expectation previously defined by the When method
func (e *LomsServiceMockOrderCreateExpectation) Then(i1 int64, err error) *LomsServiceMock {
	e.results = &LomsServiceMockOrderCreateResults{i1, err}
	return e.mock
}

// Times sets number of times LomsService.OrderCreate should be invoked
func (mmOrderCreate *mLomsServiceMockOrderCreate) Times(n uint64) *mLomsServiceMockOrderCreate {
	if n == 0 {
		mmOrderCreate.mock.t.Fatalf("Times of LomsServiceMock.OrderCreate mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmOrderCreate.expectedInvocations, n)
	mmOrderCreate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmOrderCreate
}

func (mmOrderCreate *mLomsServiceMockOrderCreate) invocationsDone() bool {
	if len(mmOrderCreate.expectations) == 0 && mmOrderCreate.defaultExpectation == nil && mmOrderCreate.mock.funcOrderCreate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmOrderCreate.mock.afterOrderCreateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmOrderCreate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// OrderCreate implements mm_service.LomsService
func (mmOrderCreate *LomsServiceMock) OrderCreate(ctx context.Context, userID model.UserID, reportCart *model.ReportCart) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmOrderCreate.beforeOrderCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmOrderCreate.afterOrderCreateCounter, 1)

	mmOrderCreate.t.Helper()

	if mmOrderCreate.inspectFuncOrderCreate != nil {
		mmOrderCreate.inspectFuncOrderCreate(ctx, userID, reportCart)
	}

	mm_params := LomsServiceMockOrderCreateParams{ctx, userID, reportCart}

	// Record call args
	mmOrderCreate.OrderCreateMock.mutex.Lock()
	mmOrderCreate.OrderCreateMock.callArgs = append(mmOrderCreate.OrderCreateMock.callArgs, &mm_params)
	mmOrderCreate.OrderCreateMock.mutex.Unlock()

	for _, e := range mmOrderCreate.OrderCreateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmOrderCreate.OrderCreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmOrderCreate.OrderCreateMock.defaultExpectation.Counter, 1)
		mm_want := mmOrderCreate.OrderCreateMock.defaultExpectation.params
		mm_want_ptrs := mmOrderCreate.OrderCreateMock.defaultExpectation.paramPtrs

		mm_got := LomsServiceMockOrderCreateParams{ctx, userID, reportCart}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmOrderCreate.t.Errorf("LomsServiceMock.OrderCreate got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderCreate.OrderCreateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmOrderCreate.t.Errorf("LomsServiceMock.OrderCreate got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderCreate.OrderCreateMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.reportCart != nil && !minimock.Equal(*mm_want_ptrs.reportCart, mm_got.reportCart) {
				mmOrderCreate.t.Errorf("LomsServiceMock.OrderCreate got unexpected parameter reportCart, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmOrderCreate.OrderCreateMock.defaultExpectation.expectationOrigins.originReportCart, *mm_want_ptrs.reportCart, mm_got.reportCart, minimock.Diff(*mm_want_ptrs.reportCart, mm_got.reportCart))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmOrderCreate.t.Errorf("LomsServiceMock.OrderCreate got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmOrderCreate.OrderCreateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmOrderCreate.OrderCreateMock.defaultExpectation.results
		if mm_results == nil {
			mmOrderCreate.t.Fatal("No results are set for the LomsServiceMock.OrderCreate")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmOrderCreate.funcOrderCreate != nil {
		return mmOrderCreate.funcOrderCreate(ctx, userID, reportCart)
	}
	mmOrderCreate.t.Fatalf("Unexpected call to LomsServiceMock.OrderCreate. %v %v %v", ctx, userID, reportCart)
	return
}

// OrderCreateAfterCounter returns a count of finished LomsServiceMock.OrderCreate invocations
func (mmOrderCreate *LomsServiceMock) OrderCreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmOrderCreate.afterOrderCreateCounter)
}

// OrderCreateBeforeCounter returns a count of LomsServiceMock.OrderCreate invocations
func (mmOrderCreate *LomsServiceMock) OrderCreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmOrderCreate.beforeOrderCreateCounter)
}

// Calls returns a list of arguments used in each call to LomsServiceMock.OrderCreate.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmOrderCreate *mLomsServiceMockOrderCreate) Calls() []*LomsServiceMockOrderCreateParams {
	mmOrderCreate.mutex.RLock()

	argCopy := make([]*LomsServiceMockOrderCreateParams, len(mmOrderCreate.callArgs))
	copy(argCopy, mmOrderCreate.callArgs)

	mmOrderCreate.mutex.RUnlock()

	return argCopy
}

// MinimockOrderCreateDone returns true if the count of the OrderCreate invocations corresponds
// the number of defined expectations
func (m *LomsServiceMock) MinimockOrderCreateDone() bool {
	if m.OrderCreateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.OrderCreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.OrderCreateMock.invocationsDone()
}

// MinimockOrderCreateInspect logs each unmet expectation
func (m *LomsServiceMock) MinimockOrderCreateInspect() {
	for _, e := range m.OrderCreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsServiceMock.OrderCreate at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterOrderCreateCounter := mm_atomic.LoadUint64(&m.afterOrderCreateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.OrderCreateMock.defaultExpectation != nil && afterOrderCreateCounter < 1 {
		if m.OrderCreateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsServiceMock.OrderCreate at\n%s", m.OrderCreateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsServiceMock.OrderCreate at\n%s with params: %#v", m.OrderCreateMock.defaultExpectation.expectationOrigins.origin, *m.OrderCreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcOrderCreate != nil && afterOrderCreateCounter < 1 {
		m.t.Errorf("Expected call to LomsServiceMock.OrderCreate at\n%s", m.funcOrderCreateOrigin)
	}

	if !m.OrderCreateMock.invocationsDone() && afterOrderCreateCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsServiceMock.OrderCreate at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.OrderCreateMock.expectedInvocations), m.OrderCreateMock.expectedInvocationsOrigin, afterOrderCreateCounter)
	}
}

type mLomsServiceMockStockInfo struct {
	optional           bool
	mock               *LomsServiceMock
	defaultExpectation *LomsServiceMockStockInfoExpectation
	expectations       []*LomsServiceMockStockInfoExpectation

	callArgs []*LomsServiceMockStockInfoParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsServiceMockStockInfoExpectation specifies expectation struct of the LomsService.StockInfo
type LomsServiceMockStockInfoExpectation struct {
	mock               *LomsServiceMock
	params             *LomsServiceMockStockInfoParams
	paramPtrs          *LomsServiceMockStockInfoParamPtrs
	expectationOrigins LomsServiceMockStockInfoExpectationOrigins
	results            *LomsServiceMockStockInfoResults
	returnOrigin       string
	Counter            uint64
}

// LomsServiceMockStockInfoParams contains parameters of the LomsService.StockInfo
type LomsServiceMockStockInfoParams struct {
	ctx context.Context
	sku model.Sku
}

// LomsServiceMockStockInfoParamPtrs contains pointers to parameters of the LomsService.StockInfo
type LomsServiceMockStockInfoParamPtrs struct {
	ctx *context.Context
	sku *model.Sku
}

// LomsServiceMockStockInfoResults contains results of the LomsService.StockInfo
type LomsServiceMockStockInfoResults struct {
	u1  uint32
	err error
}

// LomsServiceMockStockInfoOrigins contains origins of expectations of the LomsService.StockInfo
type LomsServiceMockStockInfoExpectationOrigins struct {
	origin    string
	originCtx string
	originSku string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmStockInfo *mLomsServiceMockStockInfo) Optional() *mLomsServiceMockStockInfo {
	mmStockInfo.optional = true
	return mmStockInfo
}

// Expect sets up expected params for LomsService.StockInfo
func (mmStockInfo *mLomsServiceMockStockInfo) Expect(ctx context.Context, sku model.Sku) *mLomsServiceMockStockInfo {
	if mmStockInfo.mock.funcStockInfo != nil {
		mmStockInfo.mock.t.Fatalf("LomsServiceMock.StockInfo mock is already set by Set")
	}

	if mmStockInfo.defaultExpectation == nil {
		mmStockInfo.defaultExpectation = &LomsServiceMockStockInfoExpectation{}
	}

	if mmStockInfo.defaultExpectation.paramPtrs != nil {
		mmStockInfo.mock.t.Fatalf("LomsServiceMock.StockInfo mock is already set by ExpectParams functions")
	}

	mmStockInfo.defaultExpectation.params = &LomsServiceMockStockInfoParams{ctx, sku}
	mmStockInfo.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmStockInfo.expectations {
		if minimock.Equal(e.params, mmStockInfo.defaultExpectation.params) {
			mmStockInfo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStockInfo.defaultExpectation.params)
		}
	}

	return mmStockInfo
}

// ExpectCtxParam1 sets up expected param ctx for LomsService.StockInfo
func (mmStockInfo *mLomsServiceMockStockInfo) ExpectCtxParam1(ctx context.Context) *mLomsServiceMockStockInfo {
	if mmStockInfo.mock.funcStockInfo != nil {
		mmStockInfo.mock.t.Fatalf("LomsServiceMock.StockInfo mock is already set by Set")
	}

	if mmStockInfo.defaultExpectation == nil {
		mmStockInfo.defaultExpectation = &LomsServiceMockStockInfoExpectation{}
	}

	if mmStockInfo.defaultExpectation.params != nil {
		mmStockInfo.mock.t.Fatalf("LomsServiceMock.StockInfo mock is already set by Expect")
	}

	if mmStockInfo.defaultExpectation.paramPtrs == nil {
		mmStockInfo.defaultExpectation.paramPtrs = &LomsServiceMockStockInfoParamPtrs{}
	}
	mmStockInfo.defaultExpectation.paramPtrs.ctx = &ctx
	mmStockInfo.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmStockInfo
}

// ExpectSkuParam2 sets up expected param sku for LomsService.StockInfo
func (mmStockInfo *mLomsServiceMockStockInfo) ExpectSkuParam2(sku model.Sku) *mLomsServiceMockStockInfo {
	if mmStockInfo.mock.funcStockInfo != nil {
		mmStockInfo.mock.t.Fatalf("LomsServiceMock.StockInfo mock is already set by Set")
	}

	if mmStockInfo.defaultExpectation == nil {
		mmStockInfo.defaultExpectation = &LomsServiceMockStockInfoExpectation{}
	}

	if mmStockInfo.defaultExpectation.params != nil {
		mmStockInfo.mock.t.Fatalf("LomsServiceMock.StockInfo mock is already set by Expect")
	}

	if mmStockInfo.defaultExpectation.paramPtrs == nil {
		mmStockInfo.defaultExpectation.paramPtrs = &LomsServiceMockStockInfoParamPtrs{}
	}
	mmStockInfo.defaultExpectation.paramPtrs.sku = &sku
	mmStockInfo.defaultExpectation.expectationOrigins.originSku = minimock.CallerInfo(1)

	return mmStockInfo
}

// Inspect accepts an inspector function that has same arguments as the LomsService.StockInfo
func (mmStockInfo *mLomsServiceMockStockInfo) Inspect(f func(ctx context.Context, sku model.Sku)) *mLomsServiceMockStockInfo {
	if mmStockInfo.mock.inspectFuncStockInfo != nil {
		mmStockInfo.mock.t.Fatalf("Inspect function is already set for LomsServiceMock.StockInfo")
	}

	mmStockInfo.mock.inspectFuncStockInfo = f

	return mmStockInfo
}

// Return sets up results that will be returned by LomsService.StockInfo
func (mmStockInfo *mLomsServiceMockStockInfo) Return(u1 uint32, err error) *LomsServiceMock {
	if mmStockInfo.mock.funcStockInfo != nil {
		mmStockInfo.mock.t.Fatalf("LomsServiceMock.StockInfo mock is already set by Set")
	}

	if mmStockInfo.defaultExpectation == nil {
		mmStockInfo.defaultExpectation = &LomsServiceMockStockInfoExpectation{mock: mmStockInfo.mock}
	}
	mmStockInfo.defaultExpectation.results = &LomsServiceMockStockInfoResults{u1, err}
	mmStockInfo.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmStockInfo.mock
}

// Set uses given function f to mock the LomsService.StockInfo method
func (mmStockInfo *mLomsServiceMockStockInfo) Set(f func(ctx context.Context, sku model.Sku) (u1 uint32, err error)) *LomsServiceMock {
	if mmStockInfo.defaultExpectation != nil {
		mmStockInfo.mock.t.Fatalf("Default expectation is already set for the LomsService.StockInfo method")
	}

	if len(mmStockInfo.expectations) > 0 {
		mmStockInfo.mock.t.Fatalf("Some expectations are already set for the LomsService.StockInfo method")
	}

	mmStockInfo.mock.funcStockInfo = f
	mmStockInfo.mock.funcStockInfoOrigin = minimock.CallerInfo(1)
	return mmStockInfo.mock
}

// When sets expectation for the LomsService.StockInfo which will trigger the result defined by the following
// Then helper
func (mmStockInfo *mLomsServiceMockStockInfo) When(ctx context.Context, sku model.Sku) *LomsServiceMockStockInfoExpectation {
	if mmStockInfo.mock.funcStockInfo != nil {
		mmStockInfo.mock.t.Fatalf("LomsServiceMock.StockInfo mock is already set by Set")
	}

	expectation := &LomsServiceMockStockInfoExpectation{
		mock:               mmStockInfo.mock,
		params:             &LomsServiceMockStockInfoParams{ctx, sku},
		expectationOrigins: LomsServiceMockStockInfoExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmStockInfo.expectations = append(mmStockInfo.expectations, expectation)
	return expectation
}

// Then sets up LomsService.StockInfo return parameters for the expectation previously defined by the When method
func (e *LomsServiceMockStockInfoExpectation) Then(u1 uint32, err error) *LomsServiceMock {
	e.results = &LomsServiceMockStockInfoResults{u1, err}
	return e.mock
}

// Times sets number of times LomsService.StockInfo should be invoked
func (mmStockInfo *mLomsServiceMockStockInfo) Times(n uint64) *mLomsServiceMockStockInfo {
	if n == 0 {
		mmStockInfo.mock.t.Fatalf("Times of LomsServiceMock.StockInfo mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmStockInfo.expectedInvocations, n)
	mmStockInfo.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmStockInfo
}

func (mmStockInfo *mLomsServiceMockStockInfo) invocationsDone() bool {
	if len(mmStockInfo.expectations) == 0 && mmStockInfo.defaultExpectation == nil && mmStockInfo.mock.funcStockInfo == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmStockInfo.mock.afterStockInfoCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmStockInfo.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// StockInfo implements mm_service.LomsService
func (mmStockInfo *LomsServiceMock) StockInfo(ctx context.Context, sku model.Sku) (u1 uint32, err error) {
	mm_atomic.AddUint64(&mmStockInfo.beforeStockInfoCounter, 1)
	defer mm_atomic.AddUint64(&mmStockInfo.afterStockInfoCounter, 1)

	mmStockInfo.t.Helper()

	if mmStockInfo.inspectFuncStockInfo != nil {
		mmStockInfo.inspectFuncStockInfo(ctx, sku)
	}

	mm_params := LomsServiceMockStockInfoParams{ctx, sku}

	// Record call args
	mmStockInfo.StockInfoMock.mutex.Lock()
	mmStockInfo.StockInfoMock.callArgs = append(mmStockInfo.StockInfoMock.callArgs, &mm_params)
	mmStockInfo.StockInfoMock.mutex.Unlock()

	for _, e := range mmStockInfo.StockInfoMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.u1, e.results.err
		}
	}

	if mmStockInfo.StockInfoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStockInfo.StockInfoMock.defaultExpectation.Counter, 1)
		mm_want := mmStockInfo.StockInfoMock.defaultExpectation.params
		mm_want_ptrs := mmStockInfo.StockInfoMock.defaultExpectation.paramPtrs

		mm_got := LomsServiceMockStockInfoParams{ctx, sku}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmStockInfo.t.Errorf("LomsServiceMock.StockInfo got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStockInfo.StockInfoMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sku != nil && !minimock.Equal(*mm_want_ptrs.sku, mm_got.sku) {
				mmStockInfo.t.Errorf("LomsServiceMock.StockInfo got unexpected parameter sku, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStockInfo.StockInfoMock.defaultExpectation.expectationOrigins.originSku, *mm_want_ptrs.sku, mm_got.sku, minimock.Diff(*mm_want_ptrs.sku, mm_got.sku))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStockInfo.t.Errorf("LomsServiceMock.StockInfo got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmStockInfo.StockInfoMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStockInfo.StockInfoMock.defaultExpectation.results
		if mm_results == nil {
			mmStockInfo.t.Fatal("No results are set for the LomsServiceMock.StockInfo")
		}
		return (*mm_results).u1, (*mm_results).err
	}
	if mmStockInfo.funcStockInfo != nil {
		return mmStockInfo.funcStockInfo(ctx, sku)
	}
	mmStockInfo.t.Fatalf("Unexpected call to LomsServiceMock.StockInfo. %v %v", ctx, sku)
	return
}

// StockInfoAfterCounter returns a count of finished LomsServiceMock.StockInfo invocations
func (mmStockInfo *LomsServiceMock) StockInfoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStockInfo.afterStockInfoCounter)
}

// StockInfoBeforeCounter returns a count of LomsServiceMock.StockInfo invocations
func (mmStockInfo *LomsServiceMock) StockInfoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStockInfo.beforeStockInfoCounter)
}

// Calls returns a list of arguments used in each call to LomsServiceMock.StockInfo.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStockInfo *mLomsServiceMockStockInfo) Calls() []*LomsServiceMockStockInfoParams {
	mmStockInfo.mutex.RLock()

	argCopy := make([]*LomsServiceMockStockInfoParams, len(mmStockInfo.callArgs))
	copy(argCopy, mmStockInfo.callArgs)

	mmStockInfo.mutex.RUnlock()

	return argCopy
}

// MinimockStockInfoDone returns true if the count of the StockInfo invocations corresponds
// the number of defined expectations
func (m *LomsServiceMock) MinimockStockInfoDone() bool {
	if m.StockInfoMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.StockInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.StockInfoMock.invocationsDone()
}

// MinimockStockInfoInspect logs each unmet expectation
func (m *LomsServiceMock) MinimockStockInfoInspect() {
	for _, e := range m.StockInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsServiceMock.StockInfo at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterStockInfoCounter := mm_atomic.LoadUint64(&m.afterStockInfoCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.StockInfoMock.defaultExpectation != nil && afterStockInfoCounter < 1 {
		if m.StockInfoMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsServiceMock.StockInfo at\n%s", m.StockInfoMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsServiceMock.StockInfo at\n%s with params: %#v", m.StockInfoMock.defaultExpectation.expectationOrigins.origin, *m.StockInfoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStockInfo != nil && afterStockInfoCounter < 1 {
		m.t.Errorf("Expected call to LomsServiceMock.StockInfo at\n%s", m.funcStockInfoOrigin)
	}

	if !m.StockInfoMock.invocationsDone() && afterStockInfoCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsServiceMock.StockInfo at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.StockInfoMock.expectedInvocations), m.StockInfoMock.expectedInvocationsOrigin, afterStockInfoCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LomsServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockOrderCreateInspect()

			m.MinimockStockInfoInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LomsServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LomsServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockOrderCreateDone() &&
		m.MinimockStockInfoDone()
}
